Description of Plot_DeformedStructure
Home > Utility_Functions > Plot_DeformedStructure.m
Plot_DeformedStructure
PURPOSE
PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
SYNOPSIS
function LnHndl = Plot_DeformedStructure (Model,ElemData,U,Post,PlotOpt)
DESCRIPTION
PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
  PLOT_DEFORMEDSTRUCTURE (MODEL,ELEMDATA,U,POST,PLOTOPT)
  the function plots the deformed shape of the structural model in data structure MODEL
  based on the current displacements in vector U and the element deformations;
  the cell array ELEMDATA contains information about element properties and loading;
  POST is either the vector of the element deformations Veps, or
  a cell array with the element deformations in subfield ve of field Elem; this information
  is optional; if not given, the function assumes that all element ends are continuous;
  PLOTOPT is a data structure for plotting options with the following fields:
    MAGF : magnification factor for deformed shape (default=10)
    EList: list of elements to include in deformed shape (default all elements)
    LnStl: line style for deformed shape (default = '-', i.e. solid line)
    LnWth: line thickness for deformed shape (default = 2)
    LnClr: color for deformed shape (default = 'r', i.e. red)
    PlJnt: switch for plotting joint offsets (default='yes')
    PlCrd: switch for plotting element chord (default='no')
    PlRel: switch for plotting element releases (defaul='yes')
    HngSF: scale factor for size of release symbol (default = 1)
    HOfSF: scale factor for offset of flexural hinge symbol from element end (default = 1)
    PlBnd: switch for displaying boundary symbols (default='yes')
    BsClr: color for boundary nodes and symbols (default=[0.6 0 0.6])
    NodSF: scale factor for size of boundary symbol (default = 1)
    AHClr: display color of    axial hinges or releases
    FHClr: display color of flexural hinges or releases
    ModSF: switch for adjusting scale factor relative to element size (default = 'yes')
CROSS-REFERENCE INFORMATION
This function calls:
Get_HngPos4DefoElem GET_HNGPOS4DEFOELEM determine axial and flexural hinge position for deformed element
Get_ModelScale GET_MODELSCALE determines maximum and minimum element length in Model
Plot_BounCond PLOT_BOUNCOND plots symbols for boundary conditions of structural model
Plot_Model PLOT_MODEL plots the original or deformed geometry of the structural model
This function is called by: