Description of Q2Post
Home > Utility_Functions > Q2Post.m
Q2Post
PURPOSE
Q2POST converts the vector of basic forces Q to cell array Post.Elem{}
SYNOPSIS
function Post = Q2Post (Model,Q)
DESCRIPTION
Q2POST converts the vector of basic forces Q to cell array Post.Elem{}
  POST = Q2POST(MODEL,Q)
  the function converts the basic force values in vector Q to
  the data structure POST consisting of the field Elem{el}
  for each el of the structural model in data structure MODEL
  which, in turn, contains the field Elem{el}.q with the basic forces
  of the particular element; the function uses information
  about missing basic forces in Q based on the field Model.Qmis;
  any missing basic forces are set to zero in Elem{el}.q
CROSS-REFERENCE INFORMATION
This function calls:
D_index D_INDEX cell array of indices into structure arrays for non-zero element deformations
This function is called by:
Label_2dMoments LABEL_2dMOMENTS label end moment values for 2d frame elements in current window
Label_AxialForces LABEL_AXIALFORCES label axial force values in current window
Plot_2dCurvDistr PLOT_2dCURVDISTR plot curvature distribution of 2d linear elastic frame elements
Plot_2dMomntDistr PLOT_2dMOMNTDISTR plots moment distribution for 2d frame elements in current window
Plot_AxialForces PLOT_AXIALFORCES plot axial forces in current window
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window